import React from 'react';
import {Truck,MapPin,Flag,Handshake,Send,ShieldCheck,ArrowUpRight,Package} from 'lucide-react';
import TruckIllustration from './TruckIllustration';
// Each page gets a distinct decorative scene; none represents live tracking or real photos.
export default function PageScene({label}){
 const type=label==='OUR STORY'?'story':label==='LET’S HAUL'?'fleet':label==='GROW TOGETHER'?'people':'contact';
 return <div className={'page-scene scene-'+type} aria-hidden="true"><div className="scene-halo"/><div className="scene-sun"/><div className="scene-cloud"/><span className="scene-star">✦</span>
 <svg className="scene-road" viewBox="0 0 540 420" fill="none"><path d={type==='fleet'?'M-50 305L580 180':type==='people'?'M-20 355Q230 355 260 200T565 65':'M-20 330H345Q510 330 465 205Q445 150 320 160H220Q70 170 100 30'} stroke="#a7bfdf" strokeWidth="62"/><path d={type==='fleet'?'M-50 305L580 180':type==='people'?'M-20 355Q230 355 260 200T565 65':'M-20 330H345Q510 330 465 205Q445 150 320 160H220Q70 170 100 30'} stroke="#234f86" strokeWidth="50"/><path className="scene-road-markings" d={type==='fleet'?'M-50 305L580 180':type==='people'?'M-20 355Q230 355 260 200T565 65':'M-20 330H345Q510 330 465 205Q445 150 320 160H220Q70 170 100 30'} stroke="#ffe07d" strokeWidth="3" strokeDasharray="15 15"/></svg>
 {type==='story'&&<><div className="scene-history-sign"><Flag size={22}/><small>OUR JOURNEY BEGAN</small><strong>2009</strong><span>Still moving forward ↗</span></div><div className="scene-truck story-truck"><TruckIllustration/></div><div className="scene-destination"><MapPin size={32}/><span>NATIONWIDE, TODAY</span></div></>}
 {type==='fleet'&&<><div className="scene-truck fleet-truck-back"><TruckIllustration variant="mint"/><span>12-WHEELER WING VAN</span></div><div className="scene-truck fleet-truck-front"><TruckIllustration/><span>10-WHEELER WING VAN</span></div><div className="scene-fleet-label"><Package size={22}/><span>THE RIGHT FIT.<br/><strong>THE NEXT MOVE.</strong></span></div></>}
 {type==='people'&&<><div className="scene-people-card"><Handshake size={65}/><span>PEOPLE. PURPOSE.</span><strong>Moving forward,<br/>together.</strong></div><span className="scene-value value-safety"><ShieldCheck size={24}/>Safety first</span><span className="scene-value value-trust"><Flag size={24}/>Shared direction</span><div className="scene-small-truck"><Truck size={58}/></div></>}
 {type==='contact'&&<><div className="scene-envelope"><Send size={57}/><strong>HELLO, ALZHEN.</strong><span>Your next journey starts here.</span></div><div className="scene-address origin"><MapPin size={25}/><span>YOUR PICKUP</span></div><div className="scene-address destination"><MapPin size={25}/><span>YOUR DESTINATION</span></div><div className="scene-message"><span>Let’s connect.</span><ArrowUpRight size={21}/></div></>}
 <span className="scene-footnote">{type==='fleet'?'Fleet illustrations · See vehicle photos below':'ALZHEN TRUCKING SERVICES'}</span></div>
}
